name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: composer install

      - run: composer test

      - uses: ankane/setup-postgres@v1
        with:
          database: hightop_php_test
      - run: ADAPTER=pgsql composer test

      - uses: ankane/setup-mysql@v1
        with:
          database: hightop_php_test
      - run: ADAPTER=mysql composer test
